### ISSUE TITLE
training with japanese language

### ISSUE THREAD

**Issue by lerndeep** [VamosC/CLIP4STR#1]
is it possible to train CLIP with  other language

**Comment by VamosC** [comment]
Yes, you can sure do that. 
For example, you can choose a Multilingual-CLIP that supports japanese https://github.com/FreddeFrallan/Multilingual-CLIP. Besides, you also need to change the charset and tokenizer in https://github.com/VamosC/CLIP4STR/blob/main/strhub/data/utils.py and other files.

**Comment by VamosC** [comment]
Close due to inactivity. Feel free to re-open.
