### ISSUE TITLE
Recognize French accents

### ISSUE THREAD

**Issue by hungpn68** [VamosC/CLIP4STR#17]
Hi @mzhaoshuai , Can your model recognize French accents such as " café" , "réveillait", I tried it but it doesn't seem to detect it . Is there any way to detect it ? Hope you respond soon ! Thanks

**Comment by mzhaoshuai** [comment]
@hung2003oke 
No.

The full recognizable charset is at https://github.com/VamosC/CLIP4STR/blob/d18f2f4b98b7e3dc1a59a845a6940997a4e9c09c/configs/charset/94_full.yaml#L3

If you want to add support for other languages,check https://github.com/VamosC/CLIP4STR/issues/1

**Comment by hungpn68** [comment]
Thanks @mzhaoshuai , i'll close this issue
