### ISSUE TITLE
Bug in run bash script

### ISSUE THREAD

**Issue by Teera21** [VamosC/CLIP4STR#2]
![image](https://github.com/VamosC/CLIP4STR/assets/84917837/48bdc76c-b0e1-4cf1-8951-8555a8e849c9)
I run this in google colab and i get error in bash file, 
how can i do it for try this model.

**Comment by VamosC** [comment]
Hi, thx for your trial.

Maybe you can change https://github.com/VamosC/CLIP4STR/blob/a9f209a3c019d740f55bcb394a97f1ee720dae15/scripts/read.sh#L10
to an absolute path such as
```
/content/CLIP4STR/read.py
```

**Comment by Teera21** [comment]
I solved it as you said but there are still many other problems.

I use Colab because I can download large models with my own computer resources and cannot run them.

I will be very grateful If you can share your GitHub running notebook (in colab) files to try out this model.

Thank you in advance. If it doesn't bother you too much.

**Comment by VamosC** [comment]
Hi, Teera21~

Thx for your interest in this repo. Recently I am busy with some other projects. The colab notebook may come later.

I think the first problem is the directory. Please recheck `[Prepare data]` in the ReadMe.

 I use many relative paths in the project. Before running, make sure the paths are all correct. An absolute path may help you in some cases.

Feel free to raise any question~ I will answer it ASAP.

**Comment by Teera21** [comment]
hi... To this day, I still haven't tried it, so sad.

**Comment by VamosC** [comment]
> hi... To this day, I still haven't tried it, so sad.

Ok, that is a sad story.

Recently I am catching the deadline of CVPR. Give me some time~:cry:

**Comment by VamosC** [comment]
@Teera21 

```
!git clone https://github.com/VamosC/CLIP4STR.git
!pip install -r /content/code/clip4str/requirements.txt

!wget https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt
!mv ViT-B-16.pt /content/pretrained/clip

!wget https://github.com/VamosC/CLIP4STR/releases/download/1.0.0/clip4str_base16x16_d70bde1f2d.ckpt
!mv clip4str_base16x16_d70bde1f2d.ckpt output

!bash code/clip4str/scripts/read.sh 0 clip4str_base16x16_d70bde1f2d.ckpt /content/code/clip4str/misc/test_image
```

![image](https://github.com/VamosC/CLIP4STR/assets/26076544/34c984d7-11cd-4060-b96a-4ed6ca8a112a)

It should work like this. PLZ carefully set your directories. Then changes ALL `/PUT/YOUR/PATH/HERE` in the project to a right one.

**Comment by Teera21** [comment]
Thank you.
Your are very amazing.
I will try to run this.



ในวันที่ พ. 22 พ.ย. 2023 18:38 Chao Liang ***@***.***>
เขียนว่า:

**Comment by Teera21** [comment]
![image](https://github.com/VamosC/CLIP4STR/assets/84917837/46a8a8b2-c637-4b38-aea0-2ed98a546710)
i try to you recomend but is still to bug

![image](https://github.com/VamosC/CLIP4STR/assets/84917837/b83df5d3-0194-4142-a340-43f84f8b9d6f)


i set all config this from you same folder. 
what i wrong give me some you provide please. 

![image](https://github.com/VamosC/CLIP4STR/assets/84917837/1bcd56e9-0415-48cd-88b2-b73358c3974d)
![image](https://github.com/VamosC/CLIP4STR/assets/84917837/01630eef-437a-4783-a28f-99073bed40c8)
![image](https://github.com/VamosC/CLIP4STR/assets/84917837/276ca723-e1c0-44db-92ff-e19e2ebe0163)
![image](https://github.com/VamosC/CLIP4STR/assets/84917837/228617f2-edf3-4c4c-b502-1bc76cee30d9)

**Comment by mzhaoshuai** [comment]
@Teera21 

Hi, Teera21, do you change this line?
https://github.com/VamosC/CLIP4STR/blob/a9f209a3c019d740f55bcb394a97f1ee720dae15/strhub/models/vl_str/system.py#L22

**Comment by VamosC** [comment]
Hi， @Teera21 

Do you change this line https://github.com/VamosC/CLIP4STR/blob/a9f209a3c019d740f55bcb394a97f1ee720dae15/strhub/models/vl_str/system.py#L22

Besides, `clip_pretrained` in `vl4str.yaml` (your last image) should be the path of clip model, not the checkpoint of CLIP4STR.

Global search the phrase `/PUT/YOUR/PATH/HERE` to see what you need to do.

**Comment by Teera21** [comment]
finally is Successs!!! 
Thank you very much!!! 
hahaha 

<html>
<body>

Chao Liang
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Teera21** [comment]
finally is Successs!!!
Thank you very much!!!
hahaha

![image](https://github.com/VamosC/CLIP4STR/assets/84917837/fe1f57f5-44cf-480d-a561-06016efb7f91)


Chao Liang

**Comment by VamosC** [comment]
Happy to see that!

**Comment by VamosC** [comment]
Close due to inactivity. Feel free to re-open.
