### ISSUE TITLE
Inference only

### ISSUE THREAD

**Issue by Ly-Lynn** [VamosC/CLIP4STR#22]
I want to infer with my dataset and do not want to download the training sets, is there any way to modify the code for doing this?
![image](https://github.com/user-attachments/assets/ffc6881c-6ead-4d71-a422-1389f8f8ec84)

**Comment by mzhaoshuai** [comment]
@Ly-Lynn 

Please check

```
bash scripts/read.sh 0 clip4str_base16x16_d70bde1f2d.ckpt misc/test_images

Output:
image_1576.jpeg: Chicken
```
It should be helpful for testing images.


If you want to test on lmdb format, please check
https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/data/module.py#L28-L33

You should change them accordingly.
