### ISSUE TITLE
Training other language

### ISSUE THREAD

**Issue by SeungJaeHam** [VamosC/CLIP4STR#23]
I also referred to [#1] to proceed with learning in another language. So, I follow https://github.com/VamosC/CLIP4STR/issues/1#issuecomment-1746182921. And then download this one (https://huggingface.co/M-CLIP/XLM-Roberta-Large-Vit-L-14/resolve/main/pytorch_model.bin). I tried to run the learning after setting it to clip_pretrained, but the following error code occurred.

<loading checkpoint from /data1/home/ict07/HSJ/CLIP4STR/pretrained/clip/XLM-Roberta-Large-Vit-L-14.bin
Error executing job with overrides: ['+experiment=vl4str-large', 'model=vl4str', 'dataset=real', 'data.root_dir=/NasData/datasets/str_dataset_ub', 'model.lr=8.4e-5', 'model.batch_size=16', 'trainer.accumulate_grad_batches=8', 'trainer.max_epochs=5', 'trainer.gpus=8', 'trainer.val_check_interval=10000', 'model.clip_pretrained=/data1/home/ict07/HSJ/CLIP4STR/pretrained/clip/clip-vit-large-patch14-ko.bin']
Error in call to target 'strhub.models.vl_str.system.VL4STR':
KeyError('model')
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.>

Please tell me how to deal with it.

I set it up well for my path and trained vl4str_large.sh well using weights pretrained provided by CLIP4STR. And I renamed (https://huggingface.co/M-CLIP/XLM-Roberta-Large-Vit-L-14/resolve/main/pytorch_model.bin) pytorch_model.bin to XLM-Roberta-Large-Vit-L-14.bin.

**Comment by mzhaoshuai** [comment]
Well, it is not so simple...

You need to re-construct the model following the desgin of  https://github.com/FreddeFrallan/Multilingual-CLIP.

Besides,
- change the charset
- change the tokenzier (the encoding and decoding process)
- change the dataset
- ...

**Comment by SeungJaeHam** [comment]
I'm sorry, but can you give me more details about re-construct the model? How can I re-construct the model?

And I already change the charset, tokenizer, and dataset.

**Comment by mzhaoshuai** [comment]
I think the key should be here

https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/models/vl_str/system.py#L79

You should replace the original CLIP model witm M-CLIP, so you can get the feature of images from other languages.

Take care about the atttribute of CLIP to get features:
https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/clip/model.py#L351
https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/clip/model.py#L354

You should ensure you can get features from M-CLIP correctly.


Also, take care about operations about CLIP models

https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/models/vl_str/system.py#L83-L87

https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/models/vl_str/system.py#L390

https://github.com/VamosC/CLIP4STR/blob/ef592fed6e6422964cc5e6f792035e47fdc2fe2d/strhub/models/vl_str/system.py#L453
