### ISSUE TITLE
Error Running Code: Missing clip4str_base16x16_d70bde1f2d.ckpt Checkpoint File

### ISSUE THREAD

**Issue by Abinabi** [VamosC/CLIP4STR#24]
Hey, I tried running this code but hit an error because of the checkpoint file. Where can I download clip4str_base16x16_d70bde1f2d.ckpt?

**Comment by mzhaoshuai** [comment]
Check the README.

![image](https://github.com/user-attachments/assets/36e1b8b6-585b-4d75-8165-b83e107b6c6a)
