### ISSUE TITLE
Error locating target for VL4STR

### ISSUE THREAD

**Issue by gioivuathoi** [VamosC/CLIP4STR#3]
Thank you for your great work!
I tried to run train.py (not from pretrained) on Google Colab and getting this Error:

_Error executing job with overrides: []
Error locating target 'strhub.models.vl_str.system.VL4STR', see chained exception above.
full_key: model
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace._

I have tried to use absolute path for field "_target_" in "clip4str\configs\model\vl4str.yaml" but still get the above error.
I'm using the right hydra_core version (1.2.0) as in requirements.txt
Do you have any suggestions? Thank you!

**Comment by gioivuathoi** [comment]
UDDATE:  It's my bad
I set the _HYDRA_FULL_ERROR=1_ in the command line when run *train.py*, found out there is an error in package installation that I added in the _strhub.models.vl_str.system.py_.
I do not know how this error lead to the _Error locating target_  up there, but after fix the package installation error, I don't see the _Error locating target_ again.

**Comment by shahidalihakro** [comment]
how did you solve it, can you let me know what package did you fix ?
