### ISSUE TITLE
clip4str attention graph

### ISSUE THREAD

**Issue by dle666** [VamosC/CLIP4STR#6]
This is an excellent work and I am very much interested in the advanced effects of clip attention maps in it.

Can you share the code used to generate the clip attention graph in the paper.

Thank you very much.

**Comment by VamosC** [comment]
[cam.zip](https://github.com/VamosC/CLIP4STR/files/13694856/cam.zip)

This should work. The grad-cam code is built upon https://huggingface.co/spaces/njanakiev/gradio-openai-clip-grad-cam.

Have fun with it!

**Comment by VamosC** [comment]
Close due to in-activity. Feel free to re-open.
