### ISSUE TITLE
Inference time on CPU/GPU

### ISSUE THREAD

**Issue by ajkdrag** [VamosC/CLIP4STR#7]
It would be nice if you can add the latency results to the README as well. I am planning to use this for an industry application, but before experimenting, it would be nice to know if it's even a feasible option (since I have an SLA of like 1 sec per image).

**Comment by VamosC** [comment]
Hi, @ajkdrag 

Thx for your interest.

You can check the Table VIII for the inference time of CLIP4STR on an NVIDIA A100 40 GB GPU in the paper https://arxiv.org/pdf/2305.14014.pdf.

However, I am not sure what is the batch size the authors used for testing.

It is pretty straight-forward to figure out whether you can use `CLIP4STR-B` in your case. It is a standard 12-layer vision transformer + 2 extra transformer decoder layers.
There are many benchmarks about the inference/training speed of transformer on different devices like https://lambdalabs.com/gpu-benchmarks.

Hope this is helpful for you.

**Comment by VamosC** [comment]
Close due to inactivity. Feel free to re-open.
