### ISSUE TITLE
Convert to ONNX

### ISSUE THREAD

**Issue by YenYunn** [VamosC/CLIP4STR#9]
How can I convert a model to ONNX for inference implementation?

**Comment by VamosC** [comment]
Hi, @YenYunn 

I am not familiar with this topic.
Maybe you can refer to 
https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html
https://huggingface.co/docs/transformers/serialization
for a few suggestions.

Finally, if you do success, please seriously consider make a PR to this repo, thx!

**Comment by YenYunn** [comment]
Thanks for your reply. 
I will try it
